export const REACT_QUERY_KEYS = {
  GET_MAP_DATA: 'get-map-data',
  GET_ALL_APPLICATIONS: 'GET_ALL_APPLICATIONS',
  GET_BY_ID_APPLICATIONS: 'GET_BY_ID_APPLICATIONS',
  GET_ALL_CONTRACTS: 'GET_ALL_CONTRACTS',
  CREATE_APPLY: 'CREATE_APPLY',
}
