export const ROUTER = {
  LANDING: '/',
  HOME: '/main',
  AUTH: '/auth',
  REGISTER: '/register',
  CODE: '/code',
  NOT_FOUND: '*',
  PERSONAL_INFORMATION: 'personal-information',
  APPLY: 'apply',
  CONTRACTS: 'contracts',
  COVERAGE_INSURANCE: 'coverage-insurance',
  CROP_INSURANCE: 'crop-insurance',
  CREATE: 'create',
  EDIT: 'edit',
  PAYMENT_STATUS: 'payment-status',
  DOCUMENTS: 'documents',
  POLIS: 'polis',
  TECHNICAL_SUPPORT: 'technical-support',
  VIDEO_INSTRUCTION: 'video-instruction',
}
